PLAYABACK_STATE_UPDATER_INTERVAL = 5  # 秒
MAX_SONG_COUNT_ADD_VIA_PLAYLIST = 20
DEFAULT_SONG_COUNT_ADD_VIA_PLAYLIST = 5  # 建議 = 5
MAX_SHOWED_SONGS_IN_LIST_QUEUE = 10  # 建議 <= 20
MAX_YT_SEARCH_RESULTS = 10  # 建議 <= 15
ADD_TO_QUEUE_COLOR = 0x28FF28
LIST_QUEUE_COLOR = 0xFFCF40
PLAYING_COLOR = 0xADC8FF
